### ISSUE TITLE
Improve class exports for better tree-shaking

### ISSUE THREAD

**Issue by pedrovsp** [brazilian-utils/brazilian-utils#157]
On the issue #117 , @hyanmandian suggested a change on the way we import our functions in order to improve the tree-shaking. 

> Today we import something like that: import { isValidCPF } from" @ brazilian-utils/brazilian-utils" in a tree shakable way we import something like this: import isValidCPF from" @brazilian-utils/brazilian-utils/is-valid-cpf ";, so the babel plugin will help just replacing @brazilian-utils / brazilian-utils to @brazilian-utils/brazilian-utils. You can see something like that in date-fns or lodash libraries.`

I opened this issue so we can better discuss how to proceed with this feature.

**Comment by saculbr** [comment]
The statement about an "better tree-shakable way to export" is not really true, with modern bundlers (since webpack 4.0, that as released in fev 2018) we can safely use named exports from main package file

The sideEffects: false in package.json inform bundlers that it is safe to remove unsed named exports

https://developers.google.com/web/fundamentals/performance/optimizing-javascript/tree-shaking#what_is_tree_shaking

See the "Exports Analysis" from date-fns in bundlephia, the named exports have an variable size

![Screenshot_20201031_235307](https://user-images.githubusercontent.com/4311885/97794109-4b94ed00-1bd4-11eb-988b-fdf290c3dc2f.png)


The current @brazilian-utils/brazilian-utils package works  with Tree Shaking, with an blank project that I created with just webpack@4 and @brazilian-utils/brazilian-utils installed, the Tree Shaking works

Importing isValidCPF add only 1kb to the production bundle
![Screenshot_20201101_001137](https://user-images.githubusercontent.com/4311885/97794508-f0fe8f80-1bd9-11eb-9d95-76e5f320128b.png)

![getCities](https://user-images.githubusercontent.com/4311885/97794522-260ae200-1bda-11eb-98fa-40411b88911c.png)

**Comment by saculbr** [comment]
About Exports Analysis of [@brazilian-utils/brazilian-utils@1.0.0-rc.12](https://bundlephobia.com/result?p=@brazilian-utils/brazilian-utils@1.0.0-rc.12), they erroneously shows that using a single named export result in full bundle import, that is because they look form "multi entry" package, date-fns as example send the files unbundled ("multi entry"), which offers a better analysis of the bundle, just for analysis

![Selection_019](https://user-images.githubusercontent.com/4311885/97794724-4c318180-1bdc-11eb-8415-fbcb16875621.png)

the brazilian-utils package export just the files bundled, that works with three-shaking because of sideEffects: false in package.json

**Comment by hyanmandian** [comment]
WOWWW nice job @saculbr . This info that you share here, makes me think that we don't need to do anything in our project related to tree shaking. I will close this issue. Thanks @saculbr !
